[Display.Basic]
resolutions = [
    [1920, 1080], 
    [1280, 720], 
    [1024, 768], 
    [800, 600], 
    [640, 480]
]
pref_resolution = [1920, 1080]
fullscreen = false
borderless = false
target_fps = 60

[Display.Advanced]


[Debug]
enabled = false
logging = false
display = false
hot_swap_config = false